@startuml
title Quy trinh lam De cua Son

start
:Tao thu muc /root/baitap;
:Doc /etc/passwd;
:Dem user he thong va kiem tra UID=100;
:Loc user co UID=100 va GID=100;
:Ghi danh sach vao /root/baitap/dsuser;
:Doc /etc/group va dem nhom he thong;
:Tao nhom hocvien, admin, user;
:Tao user hv1, hv2, hv3, user1, user2;
:Xoa user hv3;
:Cap quyen 640 cho dsuser;
:Dat umask 027;
:Tao tap tin va thu muc mau;
:Dang nhap user1 va thu doc dsuser;
stop

@enduml
